import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from './ThemeProvider';

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
          {children}
          </body>
    </html>
  );
}

export const metadata = {
  title: "Wael Fezari's Portfolio",
  description: "Generated by create next app",
};
